# Generated by Django 4.2.1 on 2023-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('imageLink', models.CharField(blank=True, max_length=500, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=500, null=True)),
                ('site', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
